### ISSUE TITLE
Rename "development" branch to "develop"

### ISSUE THREAD

**Issue by BasilBibi** [BasilBibi/PY-scratch#10]
"gitflow" is a common workflow model for teams using git.

https://datasift.github.io/gitflow/IntroducingGitFlow.html

In that workflow the development branch is actually called develop.

This issue is to rename our development branch to develop to conform to this standard.

Please make the develop branch the default branch github.

**Comment by HannahBibi** [comment]
Deleted the old development branch and renamed it develop as per instruction. 
Used the following to do so:

git pull origin :development
git pull origin develop

The first command deleted the development branch on github and the second renamed the branch develop.

**Comment by BasilBibi** [comment]
Hannah was not able to make develop the default branch so I did it.

**Comment by BasilBibi** [comment]
Let seems that we lost some changes and have re created develop from master.
