### ISSUE TITLE
Restructure project to conform to recommended folder layout.

### ISSUE THREAD

**Issue by BasilBibi** [BasilBibi/PY-scratch#9]
The project is currently organised as follows : 

|-src
   |---main
   |-----python
   |---test
   |-----python

Use information from this stacktrace posting to restructure the project : 

https://stackoverflow.com/questions/193161/what-is-the-best-project-structure-for-a-python-application

**Comment by HannahBibi** [comment]
Ordered and reformed project folders as follows:

|-src
|--main
|---python
|----project
|----tests
|-.gitignore
|-README.md
